#
# <meta:header>
#   <meta:licence>
#     Copyright (c) 2020, ROE (http://www.roe.ac.uk/)
#
#     This information is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This information is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#   </meta:licence>
# </meta:header>
#
#

- name: "Create our Kafka nodes"
  gather_facts: false
  hosts: localhost
  vars_files:
    - /tmp/ansible-vars.yml
  tasks:

    - name: "Create a security group for our Kafka nodes"
      os_security_group:
        cloud: "{{ cloudname }}"
        state: present
        name: "{{ security['kafkas'] }}"
      register:
        kafkasecurity

    - name: "Add a security rule to allow SSH from our gateway"
      os_security_group_rule:
        cloud: "{{ cloudname }}"
        state: present
        security_group: "{{ kafkasecurity.id }}"
        direction: 'ingress'
        protocol:  'tcp'
        port_range_min: 22
        port_range_max: 22
        remote_group: "{{ security['gateway'] }}"

    - name: "Create our Kafka nodes"
      os_server:
        cloud: "{{ cloudname }}"
        state: present
        name:     "{{ item }}"
        image:    "{{ hostvars[item]['image']  }}"
        flavor:   "{{ hostvars[item]['flavor'] }}"
        network:  "{{ networks['internal'] }}"
        key_name: "{{ keypair }}"
        auto_ip: no
        meta:
          "hostname={{ item }}"
        security_groups:
          - "{{ kafkasecurity.id }}"
      loop:
        "{{ groups['kafkas'] }}"
      register:
        kafkanodes

    - name: "Create our Kafka data volumes"
      include_tasks: tasks/openstack-volumes.yml
      loop: "{{ groups['kafkas'] }}"
      loop_control:
        loop_var: vmname

